# Generated by Django 5.1.4 on 2024-12-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_latefeeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='latefeeconfig',
            name='late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Late fee per day in currency units (e.g., 1.00 for $1.00)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='latefeeconfig',
            name='days_before_late_fee',
            field=models.PositiveIntegerField(default=14, help_text='Number of days before late fee is applied'),
        ),
    ]
