# Generated by Django 5.1.4 on 2025-01-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_borrow_due_date'),
        ('users', '0004_latefeeconfig_late_fee_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorited_by', to='books.book'),
        ),
    ]
