# Generated by Django 5.1.4 on 2024-12-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
