# Generated by Django 5.1.4 on 2024-12-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
