# Generated by Django 5.1.4 on 2024-12-28 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_borrow_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 1, 12)),
        ),
    ]
