# Generated by Django 5.1.4 on 2024-12-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_borrow_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
