# Generated by Django 5.1.4 on 2025-01-12 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_num_ratings_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 1, 27)),
        ),
    ]
